const resObj = [
  {
    cuisines: [
      "North Indian",
      "South Indian",
      "Chinese",
      "Beverages",
      "Fast Food",
      "Desserts",
    ],
    avgRating: 3.2,
    costForTwo: "₹200 for two",
    name: "Hotel Sai",
    id: 1,
    cloudinaryImageId: "vkhcohhmqfczycw9vsar",
  },
  {
    cuisines: [
      "North Indian",
      "South Indian",
      "Chinese",
      "Beverages",
      "Fast Food",
      "Desserts",
    ],
    avgRating: 4.2,
    id: 2,
    costForTwo: "₹200 for two",
    name: "KFC",
    cloudinaryImageId: "mt2aggiscfl3yviatwng",
  },
  {
    cuisines: [
      "North Indian",
      "South Indian",
      "Chinese",
      "Beverages",
      "Fast Food",
      "Desserts",
    ],
    avgRating: 4.2,
    id: 3,
    costForTwo: "₹200 for two",
    name: "Burger King",
    cloudinaryImageId: "xvyrclhxftulsglktaek",
  },
  {
    cuisines: [
      "North Indian",
      "South Indian",
      "Chinese",
      "Beverages",
      "Fast Food",
      "Desserts",
    ],
    avgRating: 4.2,
    id: 4,
    costForTwo: "₹200 for two",
    name: "Domino's",
    cloudinaryImageId: "gp1ityra6utvzqn6ghnv",
  },
  {
    cuisines: [
      "Italian",
      "Pizza",
      "Pasta",
      "Desserts",
    ],
    avgRating: 4.5,
    id: 5,
    costForTwo: "₹500 for two",
    name: "Pizza Hut",
    cloudinaryImageId: "xvyrclhxftulsglktaek",
  },
  {
    cuisines: [
      "American",
      "Burgers",
      "Fries",
      "Beverages",
    ],
    avgRating: 4.3,
    id: 6,
    costForTwo: "₹400 for two",
    name: "McDonald's",
    cloudinaryImageId: "enj3srsnhbltbom2ovvh",
  },
  {
    cuisines: [
      "Indian",
      "Biryani",
      "Fast Food",
    ],
    avgRating: 4.1,
    id: 7,
    costForTwo: "₹300 for two",
    name: "Biryani Blues",
    cloudinaryImageId: "mt2aggiscfl3yviatwng",
  },
  {
    cuisines: [
      "Mexican",
      "Tacos",
      "Fast Food",
    ],
    avgRating: 4.0,
    id: 8,
    costForTwo: "₹250 for two",
    name: "Taco Bell",
    cloudinaryImageId: "enj3srsnhbltbom2ovvh",
  },
  {
    cuisines: [
      "Indian",
      "Vegetarian",
      "Fast Food",
    ],
    avgRating: 4.6,
    id: 9,
    costForTwo: "₹350 for two",
    name: "Haldiram's",
    cloudinaryImageId: "n7wbtvlifwbw5y4a7rrv",
  },
  {
    cuisines: [
      "Desserts",
      "Ice Cream",
      "Shakes",
    ],
    avgRating: 4.7,
    id: 10,
    costForTwo: "₹150 for two",
    name: "Cream Stone",
    cloudinaryImageId: "rvxp5xbniat84r6efku2",
  },
];

export default resObj